name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  test_release:
    strategy:
      matrix:
        os: [self-hosted, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test --release -- --nocapture

  test_wasm:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install wasmtime
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash
        echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH
    - name: Install cargo-wasi
      run: cargo install cargo-wasi
    - name: Test without SIMD
      run: cargo wasi test --release -- --nocapture
    - name: Test with SIMD
      run: |
        rustup install nightly
        RUSTFLAGS="-C target-feature=+simd128" cargo +nightly wasi test --release -- --nocapture

  test_aarch64:
    runs-on: self-hosted
    name: Test on ubuntu-18.04 armv7
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run tests
        with:
          arch: aarch64
          distro: ubuntu18.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          run: |
            rustup update
            cargo build --release
            cargo test --release -- --nocapture

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Rustfmt
      run: cargo fmt --check --verbose
    - name: Clippy
      run: cargo clippy --verbose --all-features -- -Dwarnings
